### ISSUE TITLE
What is the data transmitted to the classify function?

### ISSUE THREAD

**Issue by tongvanduc** [juliardi/C45#1]
I am not sure how the data transmission needs the class part. Help me please

**Comment by juliardi** [comment]
I have added an example in the README.md 
```php
$testingData = [
  'outlook' => 'sunny',
  'windy' => 'false',
  'humidity' => 'high',
];

echo $tree->classify($testingData); // prints 'no'
```
In summary, the `data` array passed to the `classify` function is an array in the format : 
```php
[
   'attribute` => 'value'
]
```

**Comment by tongvanduc** [comment]
Thank you so much!

**Comment by juliardi** [comment]
I forgot to say, but you must execute `composer update` first. There is an update for CSV reader dependency. Also, please confirm if your problem has been resolved so I can close this issue.

**Comment by tongvanduc** [comment]
I have handled it. Thank you!
